
use grappe1;

--
-- Volcado de datos para la tabla `administrador`
--

INSERT INTO `administrador` (`Nombre`, `Apellidos`, `Email`, `Contraseña`) VALUES
('Juan', 'Perez', 'juanperez@gmail.com', '$2b$12$abc123'),
('María', 'Gómez', 'mariagomez@hotmail.com', '$2b$12$def456'),
('Pedro', 'López', 'pedrolopez@gmail.com', '$2b$12$ghi789'),
('Laura', 'Martínez', 'lauramartinez@hotmail.com', '$2b$12$jkl012'),
('Carlos', 'González', 'carlosgonzalez@gmail.com', '$2b$12$mno345'),
('Ana', 'Rodríguez', 'anarodriguez@hotmail.com', '$2b$12$pqr678'),
('José', 'Hernández', 'josehernandez@gmail.com', '$2b$12$stu901'),
('Sofía', 'Díaz', 'sofiadiaz@hotmail.com', '$2b$12$vwx234'),
('Jorge', 'Pérez', 'jorgeperez@gmail.com', '$2b$12$yza567'),
('Lucía', 'Gómez', 'luciagomez@hotmail.com', '$2b$12$bcd890'),
('Marcela', 'López', 'marcelalopez@gmail.com', '$2b$12$efg123'),
('Daniel', 'Martínez', 'danielmartinez@hotmail.com', '$2b$12$hij456'),
('Fernanda', 'González', 'fernandagonzalez@gmail.com', '$2b$12$klm789'),
('Diego', 'Rodríguez', 'diegorodriguez@hotmail.com', '$2b$12$nop012'),
('Valeria', 'Hernández', 'valeriahernandez@gmail.com', '$2b$12$qrs345'),
('Martín', 'Díaz', 'martindiaz@hotmail.com', '$2b$12$tuv678'),
('Alejandra', 'Pérez', 'alejandraperez@gmail.com', '$2b$12$wxy901'),
('Andrés', 'Gómez', 'andresgomez@hotmail.com', '$2b$12$zab234'),
('Mariana', 'López', 'marianalopez@gmail.com', '$2b$12$cde567'),
('Eduardo', 'Martínez', 'eduardomartinez@hotmail.com', '$2b$12$fgh890'),
('Camila', 'González', 'camilagonzalez@gmail.com', '$2b$12$ijk123'),
('Raúl', 'Rodríguez', 'raulrodriguez@hotmail.com', '$2b$12$lmn456'),
('María José', 'Hernández', 'mariajosehernandez@gmail.com', '$2b$12$opq789'),
('Luis', 'Díaz', 'luisdiaz@hotmail.com', '$2b$12$rst012'),
('Ana Sofía', 'Pérez', 'anasofiaperez@gmail.com', '$2b$12$uvw345'),
('Pablo', 'Gómez', 'pablogomez@hotmail.com', '$2b$12$xyz678'),
('Gabriela', 'López', 'gabrielalopez@gmail.com', '$2b$12$123abc'),
('Santiago', 'Martínez', 'santiagomartinez@hotmail.com', '$2b$12$456def'),
('Daniela', 'González', 'danielagonzalez@gmail.com', '$2b$12$789ghi'),
('Javier', 'Rodríguez', 'javierrodriguez@hotmail.com', '$2b$12$jklmno'),
('Valentina', 'Hernández', 'valentinahernandez@gmail.com', '$2b$12$pqrstu'),
('Felipe', 'Díaz', 'felipediaz@hotmail.com', '$2b$12$vwxyz1'),
('Paula', 'Pérez', 'paulaperez@gmail.com', '$2b$12$234abc'),
('Diego', 'Gómez', 'diegogomez@hotmail.com', '$2b$12$567def'),
('María Fernanda', 'López', 'mariafernandalopez@gmail.com', '$2b$12$890ghi'),
('Mateo', 'Martínez', 'mateomartinez@hotmail.com', '$2b$12$jklmno1'),
('Regina', 'González', 'reginagonzalez@gmail.com', '$2b$12$pqrstu2'),
('Sebastián', 'Rodríguez', 'sebastianrodriguez@hotmail.com', '$2b$12$vwxyz34'),
('Juliana', 'Hernández', 'julianahernandez@gmail.com', '$2b$12$567abc'),
('Martina', 'Díaz', 'martinadiaz@hotmail.com', '$2b$12$defghi');


-- --------------------------------------------------------


--
-- Volcado de datos para la tabla `cliente`
--

INSERT INTO `cliente` (`Nombre`, `Apellido`, `Email`, `Contraseña`, `Saldo`, `Numero Tarjeta`, `Titular`, `Año Vencimiento`, `Mes Vencimiento`, `CVV`) VALUES
('Carlos', 'Lopez', 'carlos.lopez@gmail.com', '$2b$12$abc123', 10000, 1234567812345678, 'Carlos Lopez', 2025, 12, 123),
('Ana', 'Martinez', 'ana.martinez@hotmail.com', '$2b$12$def456', 10000, 2345678923456789, 'Ana Martinez', 2024, 11, 456),
('Luis', 'Garcia', 'luis.garcia@gmail.com', '$2b$12$ghi789', 10000, 3456789034567890, 'Luis Garcia', 2026, 10, 789),
('Maria', 'Hernandez', 'maria.hernandez@hotmail.com', '$2b$12$jkl012', 10000, 4567890145678901, 'Maria Hernandez', 2023, 9, 12),
('Pedro', 'Fernandez', 'pedro.fernandez@gmail.com', '$2b$12$mno345', 10000, 5678901256789012, 'Pedro Fernandez', 2027, 8, 345),
('Laura', 'Gonzalez', 'laura.gonzalez@gmail.com', '$2b$12$pqr678', 10000, 6789012367890123, 'Laura Gonzalez', 2023, 7, 678),
('David', 'Perez', 'david.perez@hotmail.com', '$2b$12$stu901', 10000, 7890123478901234, 'David Perez', 2024, 6, 901),
('Jose', 'Sanchez', 'jose.sanchez@gmail.com', '$2b$12$vwx234', 10000, 8901234589012345, 'Jose Sanchez', 2025, 5, 234),
('Sandra', 'Ramirez', 'sandra.ramirez@hotmail.com', '$2b$12$yza567', 10000, 9012345690123456, 'Sandra Ramirez', 2026, 4, 567),
('Jorge', 'Torres', 'jorge.torres@gmail.com', '$2b$12$bcd890', 10000, 123456701234567, 'Jorge Torres', 2027, 3, 890),
('Lucia', 'Diaz', 'lucia.diaz@hotmail.com', '$2b$12$efg123', 10000, 1234567812345678, 'Lucia Diaz', 2023, 2, 123),
('Alberto', 'Ruiz', 'alberto.ruiz@gmail.com', '$2b$12$hij456', 10000, 2345678923456789, 'Alberto Ruiz', 2024, 1, 456),
('Pablo', 'Morales', 'pablo.morales@hotmail.com', '$2b$12$klm789', 10000, 3456789034567890, 'Pablo Morales', 2025, 12, 789),
('Monica', 'Ortiz', 'monica.ortiz@gmail.com', '$2b$12$nop012', 10000, 4567890145678901, 'Monica Ortiz', 2026, 11, 12),
('Raul', 'Gutierrez', 'raul.gutierrez@hotmail.com', '$2b$12$qrs345', 10000, 5678901256789012, 'Raul Gutierrez', 2027, 10, 345),
('Claudia', 'Ramos', 'claudia.ramos@gmail.com', '$2b$12$tuv678', 10000, 6789012367890123, 'Claudia Ramos', 2023, 9, 678),
('Francisco', 'Reyes', 'francisco.reyes@hotmail.com', '$2b$12$wxy901', 10000, 7890123478901234, 'Francisco Reyes', 2024, 8, 901),
('Patricia', 'Cruz', 'patricia.cruz@gmail.com', '$2b$12$abc234', 10000, 8901234589012345, 'Patricia Cruz', 2025, 7, 234),
('Juan', 'Vargas', 'juan.vargas@hotmail.com', '$2b$12$def567', 10000, 9012345690123456, 'Juan Vargas', 2026, 6, 567),
('Alejandra', 'Castillo', 'alejandra.castillo@gmail.com', '$2b$12$ghi890', 10000, 123456701234567, 'Alejandra Castillo', 2027, 5, 890),
('Martin', 'Mendoza', 'martin.mendoza@hotmail.com', '$2b$12$jkl123', 10000, 1234567812345678, 'Martin Mendoza', 2023, 4, 123),
('Teresa', 'Silva', 'teresa.silva@gmail.com', '$2b$12$mno456', 10000, 2345678923456789, 'Teresa Silva', 2024, 3, 456),
('Manuel', 'Ortega', 'manuel.ortega@hotmail.com', '$2b$12$pqr789', 10000, 3456789034567890, 'Manuel Ortega', 2025, 2, 789),
('Elena', 'Delgado', 'elena.delgado@gmail.com', '$2b$12$stu012', 10000, 4567890145678901, 'Elena Delgado', 2026, 1, 12),
('Rafael', 'Navarro', 'rafael.navarro@hotmail.com', '$2b$12$vwx345', 10000, 5678901256789012, 'Rafael Navarro', 2027, 12, 345),
('Gabriela', 'Rojas', 'gabriela.rojas@gmail.com', '$2b$12$yza678', 10000, 6789012367890123, 'Gabriela Rojas', 2023, 11, 678),
('Miguel', 'Estrada', 'miguel.estrada@hotmail.com', '$2b$12$bcd901', 10000, 7890123478901234, 'Miguel Estrada', 2024, 10, 901),
('Carmen', 'Guerrero', 'carmen.guerrero@gmail.com', '$2b$12$efg234', 10000, 8901234589012345, 'Carmen Guerrero', 2025, 9, 234),
('Gustavo', 'Rios', 'gustavo.rios@hotmail.com', '$2b$12$hij567', 10000, 9012345690123456, 'Gustavo Rios', 2026, 8, 567),
('Rosa', 'Romero', 'rosa.romero@gmail.com', '$2b$12$klm890', 10000, 123456701234567, 'Rosa Romero', 2027, 7, 890),
('Fernando', 'Vega', 'fernando.vega@hotmail.com', '$2b$12$nop123', 10000, 1234567812345678, 'Fernando Vega', 2023, 6, 123),
('Isabel', 'Herrera', 'isabel.herrera@gmail.com', '$2b$12$qrs456', 10000, 2345678923456789, 'Isabel Herrera', 2024, 5, 456),
('Roberto', 'Lara', 'roberto.lara@hotmail.com', '$2b$12$tuv789', 10000, 3456789034567890, 'Roberto Lara', 2025, 4, 789),
('Daniela', 'Iglesias', 'daniela.iglesias@gmail.com', '$2b$12$wxy012', 10000, 4567890145678901, 'Daniela Iglesias', 2026, 3, 12),
('Andres', 'Carrillo', 'andres.carrillo@hotmail.com', '$2b$12$abc345', 10000, 5678901256789012, 'Andres Carrillo', 2027, 2, 345),
('Gloria', 'Rico', 'gloria.rico@gmail.com', '$2b$12$def678', 10000, 6789012367890123, 'Gloria Rico', 2023, 1, 678),
('Eduardo', 'Pena', 'eduardo.pena@hotmail.com', '$2b$12$ghi901', 10000, 7890123478901234, 'Eduardo Pena', 2024, 12, 901),
('Veronica', 'Reyes', 'veronica.reyes@gmail.com', '$2b$12$jkl234', 10000, 8901234589012345, 'Veronica Reyes', 2025, 11, 234);


-- --------------------------------------------------------

--
-- Volcado de datos para la tabla `categoria`
--

INSERT INTO `categoria` (`id_categoria`, `Nombre`, `Descripcion`) VALUES 
(1, "beauty", "Productos de belleza y cuidado personal"),
(2, "fragrances", "Perfumes y fragancias"),
(3, "furniture", "Muebles y decoración para el hogar"),
(4, "groceries", "Productos de supermercado"),
(5, "home-decoration", "Artículos de decoración para el hogar"),
(6, "kitchen-accessories", "Accesorios y utensilios de cocina"),
(7, "laptops", "Computadoras portátiles"),
(8, "mens-shirts", "Camisas para hombres"),
(9, "mens-shoes", "Zapatos para hombres"),
(10, "mens-watches", "Relojes para hombres"),
(11, "mobile-accessories", "Accesorios para teléfonos móviles");


-- --------------------------------------------------------

--
-- Volcado de datos para la tabla `producto`
--

INSERT INTO `producto` (`id_producto`, `Nombre`, `Precio`, `Stock`, `id_categoria`, `Descuento`, `Descripcion`, `thumbnail`, `Disponible`) VALUES 
(1, "Essence Mascara Lash Princess", 9.99, 5, 1, 7.17, "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.", "https://cdn.dummyjson.com/products/images/beauty/Essence%20Mascara%20Lash%20Princess/thumbnail.png", "1"),
(2, "Eyeshadow Palette with Mirror", 19.99, 44, 1, 5.5, "The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it's convenient for on-the-go makeup application.", "https://cdn.dummyjson.com/products/images/beauty/Eyeshadow%20Palette%20with%20Mirror/thumbnail.png", "1"),
(3, "Powder Canister", 14.99, 59, 1, 18.14, "The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.", "https://cdn.dummyjson.com/products/images/beauty/Powder%20Canister/thumbnail.png", "1"),
(4, "Red Lipstick", 12.99, 68, 1, 19.03, "The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish.", "https://cdn.dummyjson.com/products/images/beauty/Red%20Lipstick/thumbnail.png", "1"),
(5, "Red Nail Polish", 8.99, 71, 1, 2.46, "The Red Nail Polish offers a rich and glossy red hue for vibrant and polished nails. With a quick-drying formula, it provides a salon-quality finish at home.", "https://cdn.dummyjson.com/products/images/beauty/Red%20Nail%20Polish/thumbnail.png", "1"),
(6, "Calvin Klein CK One", 49.99, 17, 2, 0.32, "CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent. It's a versatile fragrance suitable for everyday wear.", "https://cdn.dummyjson.com/products/images/fragrances/Calvin%20Klein%20CK%20One/thumbnail.png", "1"),
(7, "Chanel Coco Noir Eau De", 129.99, 41, 2, 18.64, "Coco Noir by Chanel is an elegant and mysterious fragrance, featuring notes of grapefruit, rose, and sandalwood. Perfect for evening occasions.", "https://cdn.dummyjson.com/products/images/fragrances/Chanel%20Coco%20Noir%20Eau%20De/thumbnail.png", "1"),
(8, "Dior J'adore", 89.99, 91, 2, 17.44, "J'adore by Dior is a luxurious and floral fragrance, known for its blend of ylang-ylang, rose, and jasmine. It embodies femininity and sophistication.", "https://cdn.dummyjson.com/products/images/fragrances/Dior%20J'adore/thumbnail.png", "1"),
(9, "Dolce Shine Eau de", 69.99, 3, 2, 11.47, "Dolce Shine by Dolce & Gabbana is a vibrant and fruity fragrance, featuring notes of mango, jasmine, and blonde woods. It's a joyful and youthful scent.", "https://cdn.dummyjson.com/products/images/fragrances/Dolce%20Shine%20Eau%20de/thumbnail.png", "1"),
(10, "Gucci Bloom Eau de", 79.99, 93, 2, 8.9, "Gucci Bloom by Gucci is a floral and captivating fragrance, with notes of tuberose, jasmine, and Rangoon creeper. It's a modern and romantic scent.", "https://cdn.dummyjson.com/products/images/fragrances/Gucci%20Bloom%20Eau%20de/thumbnail.png", "1"),
(11, "Annibale Colombo Bed", 1899.99, 47, 3, 0.29, "The Annibale Colombo Bed is a luxurious and elegant bed frame, crafted with high-quality materials for a comfortable and stylish bedroom.", "https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Bed/thumbnail.png", "1"),
(12, "Annibale Colombo Sofa", 2499.99, 16, 3, 18.54, "The Annibale Colombo Sofa is a sophisticated and comfortable seating option, featuring exquisite design and premium upholstery for your living room.", "https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Sofa/thumbnail.png", "1"),
(13, "Bedside Table African Cherry", 299.99, 16, 3, 9.58, "The Bedside Table in African Cherry is a stylish and functional addition to your bedroom, providing convenient storage space and a touch of elegance.", "https://cdn.dummyjson.com/products/images/furniture/Bedside%20Table%20African%20Cherry/thumbnail.png", "1"),
(14, "Knoll Saarinen Executive Conference Chair", 499.99, 47, 3, 15.23, "The Knoll Saarinen Executive Conference Chair is a modern and ergonomic chair, perfect for your office or conference room with its timeless design.", "https://cdn.dummyjson.com/products/images/furniture/Knoll%20Saarinen%20Executive%20Conference%20Chair/thumbnail.png", "1"),
(15, "Wooden Bathroom Sink With Mirror", 799.99, 95, 3, 11.22, "The Wooden Bathroom Sink with Mirror is a unique and stylish addition to your bathroom, featuring a wooden sink countertop and a matching mirror.", "https://cdn.dummyjson.com/products/images/furniture/Wooden%20Bathroom%20Sink%20With%20Mirror/thumbnail.png", "1"),
(16, "Apple", 1.99, 9, 4, 1.97, "Fresh and crisp apples, perfect for snacking or incorporating into various recipes.", "https://cdn.dummyjson.com/products/images/groceries/Apple/thumbnail.png", "1"),
(17, "Beef Steak", 12.99, 96, 4, 17.99, "High-quality beef steak, great for grilling or cooking to your preferred level of doneness.", "https://cdn.dummyjson.com/products/images/groceries/Beef%20Steak/thumbnail.png", "1"),
(18, "Cat Food", 8.99, 13, 4, 9.57, "Nutritious cat food formulated to meet the dietary needs of your feline friend.", "https://cdn.dummyjson.com/products/images/groceries/Cat%20Food/thumbnail.png", "1"),
(19, "Chicken Meat", 9.99, 69, 4, 10.46, "Fresh and tender chicken meat, suitable for various culinary preparations.", "https://cdn.dummyjson.com/products/images/groceries/Chicken%20Meat/thumbnail.png", "1"),
(20, "Cooking Oil", 4.99, 22, 4, 18.89, "Versatile cooking oil suitable for frying, sautéing, and various culinary applications.", "https://cdn.dummyjson.com/products/images/groceries/Cooking%20Oil/thumbnail.png", "1"),
(21, "Cucumber", 1.49, 22, 4, 11.44, "Crisp and hydrating cucumbers, ideal for salads, snacks, or as a refreshing side.", "https://cdn.dummyjson.com/products/images/groceries/Cucumber/thumbnail.png", "1"),
(22, "Dog Food", 10.99, 40, 4, 18.15, "Specially formulated dog food designed to provide essential nutrients for your canine companion.", "https://cdn.dummyjson.com/products/images/groceries/Dog%20Food/thumbnail.png", "1"),
(23, "Eggs", 2.99, 10, 4, 5.8, "Fresh eggs, a versatile ingredient for baking, cooking, or breakfast.", "https://cdn.dummyjson.com/products/images/groceries/Eggs/thumbnail.png", "1"),
(24, "Fish Steak", 14.99, 99, 4, 7, "Quality fish steak, suitable for grilling, baking, or pan-searing.", "https://cdn.dummyjson.com/products/images/groceries/Fish%20Steak/thumbnail.png", "1"),
(25, "Green Bell Pepper", 1.29, 89, 4, 15.5, "Fresh and vibrant green bell pepper, perfect for adding color and flavor to your dishes.", "https://cdn.dummyjson.com/products/images/groceries/Green%20Bell%20Pepper/thumbnail.png", "1"),
(26, "Green Chili Pepper", 0.99, 8, 4, 18.51, "Spicy green chili pepper, ideal for adding heat to your favorite recipes.", "https://cdn.dummyjson.com/products/images/groceries/Green%20Chili%20Pepper/thumbnail.png", "1"),
(27, "Honey Jar", 6.99, 25, 4, 1.91, "Pure and natural honey in a convenient jar, perfect for sweetening beverages or drizzling over food.", "https://cdn.dummyjson.com/products/images/groceries/Honey%20Jar/thumbnail.png", "1"),
(28, "Ice Cream", 5.49, 76, 4, 7.58, "Creamy and delicious ice cream, available in various flavors for a delightful treat.", "https://cdn.dummyjson.com/products/images/groceries/Ice%20Cream/thumbnail.png", "1"),
(29, "Juice", 3.99, 99, 4, 5.45, "Refreshing fruit juice, packed with vitamins and great for staying hydrated.", "https://cdn.dummyjson.com/products/images/groceries/Juice/thumbnail.png", "1"),
(30, "Kiwi", 2.49, 1, 4, 10.32, "Nutrient-rich kiwi, perfect for snacking or adding a tropical twist to your dishes.", "https://cdn.dummyjson.com/products/images/groceries/Kiwi/thumbnail.png", "1"),
(31, "Lemon", 0.79, 0, 4, 17.81, "Zesty and tangy lemons, versatile for cooking, baking, or making refreshing beverages.", "https://cdn.dummyjson.com/products/images/groceries/Lemon/thumbnail.png", "1"),
(32, "Milk", 3.49, 57, 4, 15.09, "Fresh and nutritious milk, a staple for various recipes and daily consumption.", "https://cdn.dummyjson.com/products/images/groceries/Milk/thumbnail.png", "1"),
(33, "Mulberry", 4.99, 79, 4, 16.35, "Sweet and juicy mulberries, perfect for snacking or adding to desserts and cereals.", "https://cdn.dummyjson.com/products/images/groceries/Mulberry/thumbnail.png", "1"),
(34, "Nescafe Coffee", 7.99, 22, 4, 11.65, "Quality coffee from Nescafe, available in various blends for a rich and satisfying cup.", "https://cdn.dummyjson.com/products/images/groceries/Nescafe%20Coffee/thumbnail.png", "1"),
(35, "Potatoes", 2.29, 8, 4, 4.05, "Versatile and starchy potatoes, great for roasting, mashing, or as a side dish.", "https://cdn.dummyjson.com/products/images/groceries/Potatoes/thumbnail.png", "1"),
(36, "Protein Powder", 19.99, 65, 4, 1.58, "Nutrient-packed protein powder, ideal for supplementing your diet with essential proteins.", "https://cdn.dummyjson.com/products/images/groceries/Protein%20Powder/thumbnail.png", "1"),
(37, "Red Onions", 1.99, 86, 4, 17.89, "Flavorful and aromatic red onions, perfect for adding depth to your savory dishes.", "https://cdn.dummyjson.com/products/images/groceries/Red%20Onions/thumbnail.png", "1"),
(38, "Rice", 5.99, 49, 4, 12.02, "High-quality rice, a staple for various cuisines and a versatile base for many dishes.", "https://cdn.dummyjson.com/products/images/groceries/Rice/thumbnail.png", "1"),
(39, "Soft Drinks", 1.99, 78, 4, 1.88, "Assorted soft drinks in various flavors, perfect for refreshing beverages.", "https://cdn.dummyjson.com/products/images/groceries/Soft%20Drinks/thumbnail.png", "1"),
(40, "Strawberry", 3.99, 9, 4, 19.59, "Sweet and succulent strawberries, great for snacking, desserts, or blending into smoothies.", "https://cdn.dummyjson.com/products/images/groceries/Strawberry/thumbnail.png", "1"),
(41, "Tissue Paper Box", 2.49, 97, 4, 15.44, "Convenient tissue paper box for everyday use, providing soft and absorbent tissues.", "https://cdn.dummyjson.com/products/images/groceries/Tissue%20Paper%20Box/thumbnail.png", "1"),
(42, "Water", 0.99, 95, 4, 13.71, "Pure and refreshing bottled water, essential for staying hydrated throughout the day.", "https://cdn.dummyjson.com/products/images/groceries/Water/thumbnail.png", "1"),
(43, "Decoration Swing", 59.99, 62, 5, 0.65, "The Decoration Swing is a charming addition to your home decor. Crafted with intricate details, it adds a touch of elegance and whimsy to any room.", "https://cdn.dummyjson.com/products/images/home-decoration/Decoration%20Swing/thumbnail.png", "1"),
(44, "Family Tree Photo Frame", 29.99, 34, 5, 1.53, "The Family Tree Photo Frame is a sentimental and stylish way to display your cherished family memories. With multiple photo slots, it tells the story of your loved ones.", "https://cdn.dummyjson.com/products/images/home-decoration/Family%20Tree%20Photo%20Frame/thumbnail.png", "1"),
(45, "House Showpiece Plant", 39.99, 89, 5, 19.45, "The House Showpiece Plant is an artificial plant that brings a touch of nature to your home without the need for maintenance. It adds greenery and style to any space.", "https://cdn.dummyjson.com/products/images/home-decoration/House%20Showpiece%20Plant/thumbnail.png", "1"),
(46, "Plant Pot", 14.99, 70, 5, 0.19, "The Plant Pot is a stylish container for your favorite plants. With a sleek design, it complements your indoor or outdoor garden, adding a modern touch to your plant display.", "https://cdn.dummyjson.com/products/images/home-decoration/Plant%20Pot/thumbnail.png", "1"),
(47, "Table Lamp", 49.99, 84, 5, 0.59, "The Table Lamp is a functional and decorative lighting solution for your living space. With a modern design, it provides both ambient and task lighting, enhancing the atmosphere.", "https://cdn.dummyjson.com/products/images/home-decoration/Table%20Lamp/thumbnail.png", "1"),
(48, "Bamboo Spatula", 7.99, 0, 6, 4.85, "The Bamboo Spatula is a versatile kitchen tool made from eco-friendly bamboo. Ideal for flipping, stirring, and serving various dishes.", "https://cdn.dummyjson.com/products/images/kitchen-accessories/Bamboo%20Spatula/thumbnail.png", "1"),
(49, "Black Aluminium Cup", 5.99, 42, 6, 9.22, "The Black Aluminium Cup is a stylish and durable cup suitable for both hot and cold beverages. Its sleek black design adds a modern touch to your drinkware collection.", "https://cdn.dummyjson.com/products/images/kitchen-accessories/Black%20Aluminium%20Cup/thumbnail.png", "1"),
(50, "Black Whisk", 9.99, 17, 6, 16.87, "The Black Whisk is a kitchen essential for whisking and beating ingredients. Its ergonomic handle and sleek design make it a practical and stylish tool.", "https://cdn.dummyjson.com/products/images/kitchen-accessories/Black%20Whisk/thumbnail.png", "1"),
(51, "Boxed Blender", 39.99, 81, 6, 7.36, "The Boxed Blender is a powerful and compact blender perfect for smoothies, shakes, and more. Its convenient design and multiple functions make it a versatile kitchen appliance.", "https://cdn.dummyjson.com/products/images/kitchen-accessories/Boxed%20Blender/thumbnail.png", "1"),
(52, "Carbon Steel Wok", 29.99, 2, 6, 5.89, "The Carbon Steel Wok is a versatile cooking pan suitable for stir-frying, sautéing, and deep frying. Its sturdy construction ensures even heat distribution for delicious meals.", "https://cdn.dummyjson.com/products/images/kitchen-accessories/Carbon%20Steel%20Wok/thumbnail.png", "1"),
(53, "Chopping Board", 12.99, 53, 6, 17.72, "The Chopping Board is an essential kitchen accessory for food preparation. Made from durable material, it provides a safe and hygienic surface for cutting and chopping.", "https://cdn.dummyjson.com/products/images/kitchen-accessories/Chopping%20Board/thumbnail.png", "1"),
(54, "Citrus Squeezer Yellow", 8.99, 59, 6, 12.35, "The Citrus Squeezer in Yellow is a handy tool for extracting juice from citrus fruits. Its vibrant color adds a cheerful touch to your kitchen gadgets.", "https://cdn.dummyjson.com/products/images/kitchen-accessories/Citrus%20Squeezer%20Yellow/thumbnail.png", "1"),
(55, "Egg Slicer", 6.99, 30, 6, 9.6, "The Egg Slicer is a convenient tool for slicing boiled eggs evenly. It's perfect for salads, sandwiches, and other dishes where sliced eggs are desired.", "https://cdn.dummyjson.com/products/images/kitchen-accessories/Egg%20Slicer/thumbnail.png", "1"),
(56, "Electric Stove", 49.99, 41, 6, 16.64, "The Electric Stove provides a portable and efficient cooking solution. Ideal for small kitchens or as an additional cooking surface for various culinary needs.", "https://cdn.dummyjson.com/products/images/kitchen-accessories/Electric%20Stove/thumbnail.png", "1"),
(57, "Fine Mesh Strainer", 9.99, 13, 6, 2.56, "The Fine Mesh Strainer is a versatile tool for straining liquids and sifting dry ingredients. Its fine mesh ensures efficient filtering for smooth cooking and baking.", "https://cdn.dummyjson.com/products/images/kitchen-accessories/Fine%20Mesh%20Strainer/thumbnail.png", "1"),
(58, "Fork", 3.99, 10, 6, 14.36, "The Fork is a classic utensil for various dining and serving purposes. Its durable and ergonomic design makes it a reliable choice for everyday use.", "https://cdn.dummyjson.com/products/images/kitchen-accessories/Fork/thumbnail.png", "1"),
(59, "Glass", 4.99, 68, 6, 7.38, "The Glass is a versatile and elegant drinking vessel suitable for a variety of beverages. Its clear design allows you to enjoy the colors and textures of your drinks.", "https://cdn.dummyjson.com/products/images/kitchen-accessories/Glass/thumbnail.png", "1"),
(60, "Grater Black", 10.99, 80, 6, 3.29, "The Grater in Black is a handy kitchen tool for grating cheese, vegetables, and more. Its sleek design and sharp blades make food preparation efficient and easy.", "https://cdn.dummyjson.com/products/images/kitchen-accessories/Grater%20Black/thumbnail.png", "1"),
(61, "Hand Blender", 34.99, 8, 6, 6.44, "The Hand Blender is a versatile kitchen appliance for blending, pureeing, and mixing. Its compact design and powerful motor make it a convenient tool for various recipes.", "https://cdn.dummyjson.com/products/images/kitchen-accessories/Hand%20Blender/thumbnail.png", "1"),
(62, "Ice Cube Tray", 5.99, 81, 6, 0.95, "The Ice Cube Tray is a practical accessory for making ice cubes in various shapes. Perfect for keeping your drinks cool and adding a fun element to your beverages.", "https://cdn.dummyjson.com/products/images/kitchen-accessories/Ice%20Cube%20Tray/thumbnail.png", "1"),
(63, "Kitchen Sieve", 7.99, 33, 6, 9.23, "The Kitchen Sieve is a versatile tool for sifting and straining dry and wet ingredients. Its fine mesh design ensures smooth results in your cooking and baking.", "https://cdn.dummyjson.com/products/images/kitchen-accessories/Kitchen%20Sieve/thumbnail.png", "1"),
(64, "Knife", 14.99, 59, 6, 19.95, "The Knife is an essential kitchen tool for chopping, slicing, and dicing. Its sharp blade and ergonomic handle make it a reliable choice for food preparation.", "https://cdn.dummyjson.com/products/images/kitchen-accessories/Knife/thumbnail.png", "1"),
(65, "Lunch Box", 12.99, 26, 6, 15.33, "The Lunch Box is a convenient and portable container for packing and carrying your meals. With compartments for different foods, it's perfect for on-the-go dining.", "https://cdn.dummyjson.com/products/images/kitchen-accessories/Lunch%20Box/thumbnail.png", "1"),
(66, "Microwave Oven", 89.99, 27, 6, 18.73, "The Microwave Oven is a versatile kitchen appliance for quick and efficient cooking, reheating, and defrosting. Its compact size makes it suitable for various kitchen setups.", "https://cdn.dummyjson.com/products/images/kitchen-accessories/Microwave%20Oven/thumbnail.png", "1"),
(67, "Mug Tree Stand", 15.99, 93, 6, 15.21, "The Mug Tree Stand is a stylish and space-saving solution for organizing your mugs. Keep your favorite mugs easily accessible and neatly displayed in your kitchen.", "https://cdn.dummyjson.com/products/images/kitchen-accessories/Mug%20Tree%20Stand/thumbnail.png", "1"),
(68, "Pan", 24.99, 40, 6, 6.55, "The Pan is a versatile and essential cookware item for frying, sautéing, and cooking various dishes. Its non-stick coating ensures easy food release and cleanup.", "https://cdn.dummyjson.com/products/images/kitchen-accessories/Pan/thumbnail.png", "1"),
(69, "Plate", 3.99, 30, 6, 13.03, "The Plate is a classic and essential dishware item for serving meals. Its durable and stylish design makes it suitable for everyday use or special occasions.", "https://cdn.dummyjson.com/products/images/kitchen-accessories/Plate/thumbnail.png", "1"),
(70, "Red Tongs", 6.99, 15, 6, 18.24, "The Red Tongs are versatile kitchen tongs suitable for various cooking and serving tasks. Their vibrant color adds a pop of excitement to your kitchen utensils.", "https://cdn.dummyjson.com/products/images/kitchen-accessories/Red%20Tongs/thumbnail.png", "1"),
(71, "Silver Pot With Glass Cap", 39.99, 37, 6, 4.57, "The Silver Pot with Glass Cap is a stylish and functional cookware item for boiling, simmering, and preparing delicious meals. Its glass cap allows you to monitor cooking progress.", "https://cdn.dummyjson.com/products/images/kitchen-accessories/Silver%20Pot%20With%20Glass%20Cap/thumbnail.png", "1"),
(72, "Slotted Turner", 8.99, 36, 6, 7.24, "The Slotted Turner is a kitchen utensil designed for flipping and turning food items. Its slotted design allows excess liquid to drain, making it ideal for frying and sautéing.", "https://cdn.dummyjson.com/products/images/kitchen-accessories/Slotted%20Turner/thumbnail.png", "1"),
(73, "Spice Rack", 19.99, 24, 6, 13.78, "The Spice Rack is a convenient organizer for your spices and seasonings. Keep your kitchen essentials within reach and neatly arranged with this stylish spice rack.", "https://cdn.dummyjson.com/products/images/kitchen-accessories/Spice%20Rack/thumbnail.png", "1"),
(74, "Spoon", 4.99, 51, 6, 0.93, "The Spoon is a versatile kitchen utensil for stirring, serving, and tasting. Its ergonomic design and durable construction make it an essential tool for every kitchen.", "https://cdn.dummyjson.com/products/images/kitchen-accessories/Spoon/thumbnail.png", "1"),
(75, "Tray", 16.99, 48, 6, 9.93, "The Tray is a functional and decorative item for serving snacks, appetizers, or drinks. Its stylish design makes it a versatile accessory for entertaining guests.", "https://cdn.dummyjson.com/products/images/kitchen-accessories/Tray/thumbnail.png", "1"),
(76, "Wooden Rolling Pin", 11.99, 80, 6, 16.94, "The Wooden Rolling Pin is a classic kitchen tool for rolling out dough for baking. Its smooth surface and sturdy handles make it easy to achieve uniform thickness.", "https://cdn.dummyjson.com/products/images/kitchen-accessories/Wooden%20Rolling%20Pin/thumbnail.png", "1"),
(77, "Yellow Peeler", 5.99, 86, 6, 17.09, "The Yellow Peeler is a handy tool for peeling fruits and vegetables with ease. Its bright yellow color adds a cheerful touch to your kitchen gadgets.", "https://cdn.dummyjson.com/products/images/kitchen-accessories/Yellow%20Peeler/thumbnail.png", "1"),
(78, "Apple MacBook Pro 14 Inch Space Grey", 1999.99, 39, 7, 9.25, "The MacBook Pro 14 Inch in Space Grey is a powerful and sleek laptop, featuring Apple's M1 Pro chip for exceptional performance and a stunning Retina display.", "https://cdn.dummyjson.com/products/images/laptops/Apple%20MacBook%20Pro%2014%20Inch%20Space%20Grey/thumbnail.png", "1"),
(79, "Asus Zenbook Pro Dual Screen Laptop", 1799.99, 38, 7, 9.21, "The Asus Zenbook Pro Dual Screen Laptop is a high-performance device with dual screens, providing productivity and versatility for creative professionals.", "https://cdn.dummyjson.com/products/images/laptops/Asus%20Zenbook%20Pro%20Dual%20Screen%20Laptop/thumbnail.png", "1"),
(80, "Huawei Matebook X Pro", 1399.99, 34, 7, 15.25, "The Huawei Matebook X Pro is a slim and stylish laptop with a high-resolution touchscreen display, offering a premium experience for users on the go.", "https://cdn.dummyjson.com/products/images/laptops/Huawei%20Matebook%20X%20Pro/thumbnail.png", "1"),
(81, "Lenovo Yoga 920", 1099.99, 71, 7, 7.77, "The Lenovo Yoga 920 is a 2-in-1 convertible laptop with a flexible hinge, allowing you to use it as a laptop or tablet, offering versatility and portability.", "https://cdn.dummyjson.com/products/images/laptops/Lenovo%20Yoga%20920/thumbnail.png", "1"),
(82, "New DELL XPS 13 9300 Laptop", 1499.99, 18, 7, 11.7, "The New DELL XPS 13 9300 Laptop is a compact and powerful device, featuring a virtually borderless InfinityEdge display and high-end performance for various tasks.", "https://cdn.dummyjson.com/products/images/laptops/New%20DELL%20XPS%2013%209300%20Laptop/thumbnail.png", "1"),
(83, "Blue & Black Check Shirt", 29.99, 44, 8, 1.41, "The Blue & Black Check Shirt is a stylish and comfortable men's shirt featuring a classic check pattern. Made from high-quality fabric, it's suitable for both casual and semi-formal occasions.", "https://cdn.dummyjson.com/products/images/mens-shirts/Blue%20&%20Black%20Check%20Shirt/thumbnail.png", "1"),
(84, "Gigabyte Aorus Men Tshirt", 24.99, 64, 8, 12.6, "The Gigabyte Aorus Men Tshirt is a cool and casual shirt for gaming enthusiasts. With the Aorus logo and sleek design, it's perfect for expressing your gaming style.", "https://cdn.dummyjson.com/products/images/mens-shirts/Gigabyte%20Aorus%20Men%20Tshirt/thumbnail.png", "1"),
(85, "Man Plaid Shirt", 34.99, 65, 8, 17.53, "The Man Plaid Shirt is a timeless and versatile men's shirt with a classic plaid pattern. Its comfortable fit and casual style make it a wardrobe essential for various occasions.", "https://cdn.dummyjson.com/products/images/mens-shirts/Man%20Plaid%20Shirt/thumbnail.png", "1"),
(86, "Man Short Sleeve Shirt", 19.99, 20, 8, 8.65, "The Man Short Sleeve Shirt is a breezy and stylish option for warm days. With a comfortable fit and short sleeves, it's perfect for a laid-back yet polished look.", "https://cdn.dummyjson.com/products/images/mens-shirts/Man%20Short%20Sleeve%20Shirt/thumbnail.png", "1"),
(87, "Men Check Shirt", 27.99, 69, 8, 14.21, "The Men Check Shirt is a classic and versatile shirt featuring a stylish check pattern. Suitable for various occasions, it adds a smart and polished touch to your wardrobe.", "https://cdn.dummyjson.com/products/images/mens-shirts/Men%20Check%20Shirt/thumbnail.png", "1"),
(88, "Nike Air Jordan 1 Red And Black", 149.99, 15, 9, 15.82, "The Nike Air Jordan 1 in Red and Black is an iconic basketball sneaker known for its stylish design and high-performance features, making it a favorite among sneaker enthusiasts and athletes.", "https://cdn.dummyjson.com/products/images/mens-shoes/Nike%20Air%20Jordan%201%20Red%20And%20Black/thumbnail.png", "1"),
(89, "Nike Baseball Cleats", 79.99, 14, 9, 11.4, "Nike Baseball Cleats are designed for maximum traction and performance on the baseball field. They provide stability and support for players during games and practices.", "https://cdn.dummyjson.com/products/images/mens-shoes/Nike%20Baseball%20Cleats/thumbnail.png", "1"),
(90, "Puma Future Rider Trainers", 89.99, 10, 9, 3.64, "The Puma Future Rider Trainers offer a blend of retro style and modern comfort. Perfect for casual wear, these trainers provide a fashionable and comfortable option for everyday use.", "https://cdn.dummyjson.com/products/images/mens-shoes/Puma%20Future%20Rider%20Trainers/thumbnail.png", "1"),
(91, "Sports Sneakers Off White & Red", 119.99, 73, 9, 11.69, "The Sports Sneakers in Off White and Red combine style and functionality, making them a fashionable choice for sports enthusiasts. The red and off-white color combination adds a bold and energetic touch.", "https://cdn.dummyjson.com/products/images/mens-shoes/Sports%20Sneakers%20Off%20White%20&%20Red/thumbnail.png", "1"),
(92, "Sports Sneakers Off White Red", 109.99, 75, 9, 17.22, "Another variant of the Sports Sneakers in Off White Red, featuring a unique design. These sneakers offer style and comfort for casual occasions.", "https://cdn.dummyjson.com/products/images/mens-shoes/Sports%20Sneakers%20Off%20White%20Red/thumbnail.png", "1"),
(93, "Brown Leather Belt Watch", 89.99, 69, 10, 15.01, "The Brown Leather Belt Watch is a stylish timepiece with a classic design. Featuring a genuine leather strap and a sleek dial, it adds a touch of sophistication to your look.", "https://cdn.dummyjson.com/products/images/mens-watches/Brown%20Leather%20Belt%20Watch/thumbnail.png", "1"),
(94, "Longines Master Collection", 1499.99, 65, 10, 0.64, "The Longines Master Collection is an elegant and refined watch known for its precision and craftsmanship. With a timeless design, it's a symbol of luxury and sophistication.", "https://cdn.dummyjson.com/products/images/mens-watches/Longines%20Master%20Collection/thumbnail.png", "1"),
(95, "Rolex Cellini Date Black Dial", 8999.99, 84, 10, 14.28, "The Rolex Cellini Date with Black Dial is a classic and prestigious watch. With a black dial and date complication, it exudes sophistication and is a symbol of Rolex's heritage.", "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Cellini%20Date%20Black%20Dial/thumbnail.png", "1"),
(96, "Rolex Cellini Moonphase", 12999.99, 33, 10, 5.7, "The Rolex Cellini Moonphase is a masterpiece of horology, featuring a moon phase complication and exquisite design. It reflects Rolex's commitment to precision and elegance.", "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Cellini%20Moonphase/thumbnail.png", "1"),
(97, "Rolex Datejust", 10999.99, 11, 10, 9.69, "The Rolex Datejust is an iconic and versatile timepiece with a date window. Known for its timeless design and reliability, it's a symbol of Rolex's watchmaking excellence.", "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Datejust/thumbnail.png", "1"),
(98, "Rolex Submariner Watch", 13999.99, 35, 10, 0.82, "The Rolex Submariner is a legendary dive watch with a rich history. Known for its durability and water resistance, it's a symbol of adventure and exploration.", "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Submariner%20Watch/thumbnail.png", "1"),
(99, "Amazon Echo Plus", 99.99, 50, 11, 16.3, "The Amazon Echo Plus is a smart speaker with built-in Alexa voice control. It features premium sound quality and serves as a hub for controlling smart home devices.", "https://cdn.dummyjson.com/products/images/mobile-accessories/Amazon%20Echo%20Plus/thumbnail.png", "1"),
(100, "Apple Airpods", 129.99, 93, 11, 4.82, "The Apple Airpods offer a seamless wireless audio experience. With easy pairing, high-quality sound, and Siri integration, they are perfect for on-the-go listening.", "https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20Airpods/thumbnail.png", "1");
